version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: subscription_tracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-subscription_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Secur3Passw0rd!}
      POSTGRES_DB: ${POSTGRES_DB:-subscription_tracker}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v18:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: subscription_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: subscription_tracker_mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped

volumes:
  postgres_data_v18:
  redis_data:
